### ISSUE TITLE
More bento4?

### ISSUE THREAD

**Issue by nunsie** [ubuntuegor/mp4decrypt-buffer#1]
Hi

Is there scope for adding additional bento4 utilities to this package? namely `mp4split` and `mp4pssh`

**Comment by ubuntuegor** [comment]
Hi, I think it's out of scope for this package, but it should be possible to implement them as well, just replace the processing logic to how specific Bento4 tools work. For this package I mostly just copied [the code](https://github.com/axiomatic-systems/Bento4/blob/master/Source/C++/Apps/) from `mp4decrypt`'s sources

**Comment by nunsie** [comment]
OK cool, thank you for the pointers!
I will try fork this repo and extend to include other utilities.
C++ isn't my native language so this is going to be tough challenge haha

Thanks again :)
