### ISSUE TITLE
update to use the latest bento4

### ISSUE THREAD

**Issue by bluchip-studio-official** [ubuntuegor/mp4decrypt-buffer#2]
Hi could this be updated to use the latest bento4 ?

i have tried using it but i get the following errors

> WARNING: atom serialized to fewer bytes than declared size
> WARNING: padding would be too large

i have checked using mp4 decrypt its self and it works so i assume its because this is using an older version

**Comment by ubuntuegor** [comment]
The [latest version](https://github.com/axiomatic-systems/Bento4/tags) is still 1.6.0-639, which is in this package. What version of mp4decrypt are you using?

**Comment by bluchip-studio-official** [comment]
[v1.6.0-640](https://github.com/axiomatic-systems/Bento4/releases/tag/v1.6.0-640)
